version: '3.3'
services:
  snappfood-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'snappfood'
      MYSQL_USER: 'dba'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '1234:3306'
    expose:
      - '1234'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: